### PR TITLE
Requesting Feedback on Security Upgrades

### PR DESCRIPTION
**Pull request by NickBorgers**
Hello,

I used your RegistrationForm codebase to create a secure web application for a business I started. It was necessary, and desirable, for me to greatly increase the degree of security. I have attempted to endow the "vanilla" site you provided with the security improvements of my site.

I would like for this more secure version to be merged so that in the future when people start a site with the RegistrationForm code they can more easily secure it, and start with a higher level of protection for their users.

I fully welcome your feedback and the issues you take with the code's current state.

### CODE REVIEW

**Comment by ug2215** [comment]
Hey guys, please let me know if you plan to review this pull request. If not, I will find some other way to distribute the code.

**Comment by prasanthmj** [comment]
Hi

Thanks for the updates. Need a couple more days to review the work

Sorry for the late reply

Regards,
Prasanth
http://www.simfatic.com

**Comment by ug2215** [comment]
No problem, just confirming.

**Comment by prasanthmj** [comment]
I reviewed the security updates. However, the original vanilla code is intended to demonstrate the basics of membership site- login & registration process. Don't want to add extra complexity of client side hashing etc. So can't take the pull request. You are free to re-puplish the update

**Comment by ug2215** [comment]
I think this is a mistake:
*) The essential reason security is a problem today is that it is not baked-in early. Do you not envision users of this software intending to grow to a point where security would be necessary and valuable?
*) The vanilla code lacks effective sanitization of visitor inputs, leaving it vulnerable to MySQL injection. In particular the mysql_real_escape_string function is deprecated by PHP: http://php.net/manual/en/function.mysql-real-escape-string.php
*) In the default configuration I published, the only added complexity which must be managed by a user of the code is handling a CSRF token with authenticated requests, for which examples are provided. However, they have the option to turn up security on the behalf of their users quote dramatically.

**Comment by masimies** [comment]
Hi,
Did you forget already this project? Or something else found as replacement?
I tried to upgrade my portal to this newer version, but it seems that there is still some bugs?
I was discussing about this here:
https://www.daniweb.com/programming/web-development/threads/503450/fg_membersite-php

I like to have this working, because it is just as what i need. Cannot use the old version anymore with less security.

**Comment by davidberriman** [comment]
I think this is a great project, but I was also concerned with the security issues so I have create a new version with some improvements which can be found here:
https://github.com/davidberriman/form_registration

**Comment by masimies** [comment]
Hi,
I allready fixed the old version, and it has been working just fine after fixes.
I looked up the new version. It's good that there is coming improvements, but with more code and libraries for my goal.
When i started my project, i create my site with current way of building up functionality. Including jquery and bootstrap. Now, when i have more expirience with coding, i have been get rid of jquery and bootstrap. Releasing over 20000-rows of code. For example, datepicker. My site needs only datepicker, for getting dates. Before, i had jguery and moment for correct date-format. After greating my own datepicker, with 300-rows code, i did not need those libraries anymore. For navigation and style, i have now used only pure css. Without huge bootstrap and jquery libraries.
Starting from amount of 120 files, decreased site to working only with 70, is current state.
My next focus is to get more lighter member-site login system. But without jquery and bootstrap prequisites again.
I know that it is harder work, to create functionalities without common libraries. Going to lighter way of creating things. That why i wait if someone like to think so as well, and start project. Or if i could have more time, focus to this also.
Br, and good luck for this new project.

**Pull request closed without merging**
